### ISSUE TITLE
how does this work?

### ISSUE THREAD

**Issue by stguitar** [fanningert/webtrees_simpleautologin#1]
I am trying to use this module (so excited that you made it)...

If I perform a GET request on any page, and provide the "REMOTE_USER" header with a valid username, should it show the authenticated version of the page?

I have set the trusted header value in the config file. 

I ultimately have different reverse proxies to use, but i was curious about what it should expect before trying to connect it.

**Comment by fanningert** [comment]
Yes, when everythink is working. You should instantly be authenticated as the REMOTE_USER.

**Comment by fanningert** [comment]
Look at this site for the details of REMOTE_USER.
https://stackoverflow.com/questions/33368653/how-do-i-set-remote-user-in-a-http-header

**Comment by stguitar** [comment]
hmm.  OK.  So I have a local version of it running with basically everything hidden visitors, and im trying to use postman to provide the REMOTE_USER header with my user name.  is to be a token or base64 or something? or just plain text? the code seems to think it is plain text.   I would have expected the page to properly display in postman bc of the addition of the header.

**Comment by stguitar** [comment]
i should also ask... does one hit the login page with this header and then you are good, or should it be present on every page request to keep the user logged in etc?

**Comment by stguitar** [comment]
one last thing... the readme file says to enable it that the checkbox should be cleared.  i assumed that was inaccurate. I have that check ON/Enabled etc.

**Comment by fanningert** [comment]
> one last thing... the readme file says to enable it that the checkbox should be cleared. i assumed that was inaccurate. I have that check ON/Enabled etc.

Yes, you are right.

**Comment by fanningert** [comment]
> hmm. OK. So I have a local version of it running with basically everything hidden visitors, and im trying to use postman to provide the REMOTE_USER header with my user name. is to be a token or base64 or something? or just plain text? the code seems to think it is plain text. I would have expected the page to properly display in postman bc of the addition of the header.

Sorry, I have no experience with postman. But I think this topic will clear the questions about REMOTE_USER.
https://stackoverflow.com/questions/33368653/how-do-i-set-remote-user-in-a-http-header
https://wiki.cac.washington.edu/display/infra/About+REMOTE_USER+and+HTTP_REMOTEUSER

The username behind REMOTE_USER is plain. Without a password or a token. So its important, that you are using https, also for local enviroment (Reverse-Proxy <-https-> webtrees webserver).

**Comment by stguitar** [comment]
Hmm, i can hit the `server info` page while logged in and I see that my apache config is manually passing the request header (just for testing).  It is included in the headers listed.

when i logout, and i try to hit the server info page while not logged in, i just get redirected to the login page (https://localhost:8088/index.php?route=%2Fadmin%2Finformation)

**Comment by stguitar** [comment]
> > hmm. OK. So I have a local version of it running with basically everything hidden visitors, and im trying to use postman to provide the REMOTE_USER header with my user name. is to be a token or base64 or something? or just plain text? the code seems to think it is plain text. I would have expected the page to properly display in postman bc of the addition of the header.
> 
> Sorry, I have no experience with postman. But I think this topic will clear the questions about REMOTE_USER. https://stackoverflow.com/questions/33368653/how-do-i-set-remote-user-in-a-http-header https://wiki.cac.washington.edu/display/infra/About+REMOTE_USER+and+HTTP_REMOTEUSER
> 
> The username behind REMOTE_USER is plain. Without a password or a token. So its important, that you are using https, also for local enviroment (Reverse-Proxy <-https-> webtrees webserver).

OK, i will give this a try - many thanks!

**Comment by fanningert** [comment]
> i should also ask... does one hit the login page with this header and then you are good, or should it be present on every page request to keep the user logged in etc?

No you don't need to click on the login page or logout. You also don't need to redirect to a login page. You can redirect to every direct link page and webtrees + addon is making a automatic login. Is the same process, when webtress without the addon is running. In this scenario, webtrees redirect to the login page and after login to the target page.

**Comment by stguitar** [comment]
OK.  Yea, i dont get why this isnt working... I have my apache setup to just always set the REMOTE_USER header with value of 'admin' for testing, so that I would have thought i would not need to login at all.   

I have this in the config ini file:
`trusted_header_authenticated_user="REMOTE_USER";`

**Comment by fanningert** [comment]
You can create a info.php page in the webtrees installation and check if the REMOTE_USER is sended from the reverse proxy.

```php
<?php
phpinfo();
?>
```

**Comment by stguitar** [comment]
Bingo!! Thanks so much for your help and support. 

What ended up being the problem is that I got to poking around in the install that im using to add the info.php page you suggested, and found that it had a governing env var on top of it to enable the support that i dont think is in their documentation. 

So in full disclosure, I am running this via docker, so its kind of up to the image im using, but i can see it is now working!  Now, just need to get it behind my AWS load balancer and use the headers off of it.

**Comment by stguitar** [comment]
I meant to ask you - do you have any interest in supporting JWT handling?  if you are interesting, i don't mind putting up a PR.  I was thinking it could be enabled via env var.

**Comment by fanningert** [comment]
JWT logic is a bit more and should be direct integrated into to webtrees (or via separate addon), but not via a authentication-proxy addon like this. JWT is a little bit more complex and cureently I have no time and test environment for this. When JWT is on the tablet, some other authentication should also integrated. SAML, OAUTH, ..
