### ISSUE TITLE
Is this module not compatible with webtrees 2.1.16?

### ISSUE THREAD

**Issue by jake404** [fanningert/webtrees_simpleautologin#4]
I have webtrees 2.1.16 and the REMOTE_USER header is sent correctly and the config.ini.php has the line trusted_header_authenticated_user="REMOTE_USER";, but it does not auto login. Is this module not compatible with webtrees 2.1.16?

**Comment by AlexBocken** [comment]
The plugin is working for me with 2.1.18. 
Does it also not work if you press "Log in" in webtrees? The plugin weirdly enough does not automatically log you in, you still need to press the button manually.
You can automate this by including some Javascript and CSS in your website. See my answer in #2 .
